const WeatherActionTypes = {
  UPDATE_CURRENT_CITY: 'UPDATE_CURRENT_CITY',
  UPDATE_CURRENT_CITY_WEATHER: 'UPDATE_CURRENT_CITY_WEATHER',
  UPDATE_SEARCH_RESULTS: 'UPDATE_SEACH_RESULTS',
  ADD_CITY_TO_FAVORITES: 'ADD_CITY_TO_FAVORITES',
  REMOVE_CITY_FROM_FAVORITES: 'REMOVE_CITY_FROM_FAVORITES'
};

export default WeatherActionTypes;
